update_fastlane

default_platform(:android)

platform :android do
  desc "Build and upload to the Google Play's internal track"
  lane :build_and_upload_internal do
    version_code = google_play_track_version_codes(track: "internal").last + 1

    build_android_app(
      task: "bundle",
      build_type: "Release",
      properties: {
        "android.injected.version.code" => version_code,
        "android.injected.version.name" => "1.0.#{version_code}",
      }
    )

    upload_to_play_store(
      track: "internal",
      skip_upload_changelogs: true,
      version_code: version_code,
      version_name: "1.0.#{version_code}",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
    )
  end

  desc "Promote Google Play's internal track to production"
  lane :promote_internal_to_production do
    upload_to_play_store(
      track: "internal",
      track_promote_to: "production",
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Build and capture screenshots"
  lane :build_and_screengrab do
    build_android_app(task: "assemble", build_type: "Debug")
    build_android_app(task: "assemble", build_type: "AndroidTest")

    screengrab()
  end
end
