update_fastlane

default_platform(:android)

platform :android do
  desc "Build and upload to the Google Play's beta track"
  lane :build_and_upload_beta do
    build_android_app(task: 'assemble', build_type: 'Release')
    upload_to_play_store(track: 'beta', skip_upload_changelogs: true)
  end

  desc "Build and capture screenshots"
  lane :build_and_screengrab do
    build_android_app(task: 'assemble', build_type: 'Debug')
    build_android_app(task: 'assemble', build_type: 'AndroidTest')

    screengrab()
  end
end
